test_suites:
  - name: docker
    script_path: /root/okta/concourse-terraform/scripts
    sort_order: '5'
    timeout: '30'
    script_name: docker
    script_env: {
    }
    criteria: MERGE
    queue_name: small
